on:
  pull_request:
    types: [opened, synchronize, edited]
  issue_comment:
    types: [created, edited]

permissions:
      issues: write
      pull-requests: write
      contents: write
      
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          CONFIG.MODEL: "gemini/gemini-2.5-flash-preview-05-20"
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.CUSTOM_MODEL_MAX_TOKENS: 64000
          github_action.auto_describe: 'true'
          github_action.auto_review: 'true'
          github_action.auto_improve: 'true'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
          PR_IMPROVE_COMPONENT.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
